### ISSUE TITLE
Errors with the latest update

### ISSUE THREAD

**Issue by AutolycusWolf** [rhodan412/ActionBarProfiles#5] opened 2024-08-24 23:28 UTC
**Which version are you using when bug occurred**
ActionBarProfiles-11.0.2.1b-release

**Describe the bug**
The profiles button doesn't appear on initial log-in (paper doll frame), fixes itself after reloading UI.

**LUA Error**
1x ...rfaceActionBarProfiles/ActionBarProfiles.lua:187: Usage: GetSpecializationInfo(specIndex[, isInspect[, isPet[, inspectTarget[, sex]]]])
[string "=[C]"]: in function `GetSpecializationInfo'
[string "@ActionBarProfiles/ActionBarProfiles.lua"]:187: in function <...rfaceActionBarProfiles/ActionBarProfiles.lua:135>
[string "=[C]"]: ?
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:494: in function `InitializeAddon'
[string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:619: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals:
(*temporary) = nil

**Comment by rhodan412** [comment] 2024-08-25 03:40
Appreciate the additional info but duplicate of #4. Updates for this issue will be posted on that earlier report

**Closed as completed by rhodan412** 2024-08-25 03:40 UTC
Labels: duplicate
